### PR TITLE
Expose team_time in Bot

### LINKED ISSUE #797: make the cumulative time counter available to clients
The `Bot` object should have an attribute `time` where the cumulative time for the team shown in the GUI is made available. This is useful for example when benchmarking different strategies. There's no way at the moment to programmatically access that value, as far as I could see.
Of course the client could time itself, but this has its own pitfalls. So it's better to just make that value available, even if we all know it's not super precise...

### PR DESCRIPTION
**Pull request by Debilski**
The test could use some more creativity.

Closes #797

### CODE REVIEW

**Comment by Debilski** [comment]
wow. Fixing these tests took way longer than expected …

**Comment by Debilski** [comment]
Pedagogic rebase

**Comment by otizonaizit** [comment]
thanks, looks good! I added a label to mark the needs for docs update in [pelita_template](https://github.com/ASPP/pelita_template/). We need to find a better way to mark these dependencies...

**Comment by Debilski** [comment]
It would be nice to have a live stopwatch running in the UI instead of only incrementally updating it, but I believe we cannot really synchronise this with the actual game state.

**Comment by Debilski** [comment]
FWIW Python 3.13 should have a more accurate `time.monotonic()` on Windows. https://github.com/python/cpython/issues/88494

**Pull request merged**
