### PR TITLE
WIP: TK-ui cleanups

### PR DESCRIPTION
**Pull request by otizonaizit**
- makes subtitle status line font smaller and more spaced from title (now the two lines should not overlap anymore (needs to be tested on anaconda and Mac)
- still some other cleanups here

### CODE REVIEW

**Comment by otizonaizit** [comment]
Looks good with anaconda on Linux too. Any Mac to test?

**Comment by Debilski** [comment]
> Any Mac to test?

Still trying to figure out why Tk breaks (on) all my systems.

**Comment by Debilski** [comment]
On Anaconda macOS it is quite spacious now. But seems ok. Can be merged.

**Comment by otizonaizit** [comment]
@Debilski : maybe we should switch off the codecov/patch check on PRs? If it would be possible to have a soft-fail, like a yellow circle, than OK. But a PR like this seems broken for no reason.
Also, could you merge this one too once pelita-core-2 is in? Thanks!

**Pull request merged**
