### PR TITLE
Show noisy enemies with a questionmark

### LINKED ISSUE #622: print(bot) should show which enemies are noisy
This will hopefully avoid confusion.

One remark: since we got rid of set_initial in the new-style API, the teams never see their enemies sitting unnoised on their initial positions, which has been a nice (and easy) starting point for filtering. Question: Do we want to be explicit about how the initial positions are fixed (ie. add an example) or do we want them to figure it out themselves?

### PR DESCRIPTION
**Pull request by Debilski**
> print(bot)

    StoppingBots (you) vs Random Explorer Players.
    Playing on blue side. Current turn: 1. Round: 2, score: 0:0. timeouts: 0:0
    ################################
    #   ..   .     ##             ?#  
    #  ## ...#  . .   ##.## ###### #
    # . # . .#        .#. #. . #   #
    # . #### ########   . #  # ?   #
    #      .   .       #  #.## #. .#
    #   #######.##     #  # #  #. .#
    #  ... #    #  ##. #  #    #   #
    #   #    #  # .##  #    # ...  #
    #. .#  # #  #     ##.#######   #
    #. .# ##.#  #       .   .      #
    #     #  # .   ######## #### . #
    #   # . .# .#.        #. . # . #
    #0###### ##.##   . .  #... ##  #
    #1             ##     .   ..   #
    ################################

Not sure if this is legible enough?

Closes #622

### CODE REVIEW

**Comment by otizonaizit** [comment]
and you would show `E` when the position is not noisy? This seems a good idea! Have you adapted also the layout_from_str function to understand the new character?

**Comment by Debilski** [comment]
> On 8. Aug 2019, at 17:42, Tiziano Zito <notifications@github.com> wrote:
> 
> and you would show E when the position is not noisy? This seems a good idea! Have you adapted also the layout_from_str function to understand the new character?
> 

Not yet. (Should have made it a draft PR.)

**Comment by Debilski** [comment]
`parse_layout` can parse the ? now but it will be the same as E. I don’t know if we want `setup_test_game` to automatically set the `is_noisy` flag, when there is a question mark?

**Comment by otizonaizit** [comment]
Sure, set is_noisy.

**Pull request merged**
