### PR TITLE
Better walls for TK UI

### PR DESCRIPTION
**Pull request by otizonaizit**
This PR increases the thickness of all walls in the TK UI. This way it is easier to see how many squares are there between wall tunnels, for example. 
Also, fill in squares of walls. Until now there is empty space within a square of walls, and it seems it would be reachable. If we go for this thickness, then maybe the color of the walls could be made a little lighter.

Two screenshots on two different layouts to appreciate the change.

Master branch (example 1):
master_branch1

This PR (example 1):
this_branch1

Master branch (example 2):
master_branch2

This PR (example 2):
this_branch2

### CODE REVIEW

**Comment by Debilski** [comment]
-0. Not sure what it is, but something is weird about that design.

I think if we want to fill it and have thick borders, maybe we should not have round corners.

**Comment by otizonaizit** [comment]
by the way, the unrelated travis ci failure are annoying. Couldn't we just skip that test until is fixed?

**Comment by otizonaizit** [comment]
> I think if we want to fill it and have thick borders, maybe we should not have round corners.

I like the round corners. Anyway, here is a proposal with less prominent walls: 1627de6
screenshot2

**Comment by lschwetlick** [comment]
I prefer the black walls. The faded version looks like theres something wrong with my screen.

**Comment by Debilski** [comment]
> I prefer the black walls. The faded version looks like theres something wrong with my screen.

Agreed. Maybe it would help to have a dark black small border around the faded wall?

**Comment by otizonaizit** [comment]
> > I prefer the black walls. The faded version looks like theres something wrong with my screen.
> 
> Agreed. Maybe it would help to have a dark black small border around the faded wall?

Unfortunately the TK `create_line` method for the canvas does not allow for an outlline in the line
object. Either we redo the whole thing using polygons, or we choose one single fill color.
You both seem to prefer the old dark brown?
@lschwetlick : do you prefer the version in this PR with thicker walls and filled-in squares or the old version with thin walls and hollow squares? (see above for the screenshots)

**Comment by otizonaizit** [comment]
Also, we are probably the worst to judge, as we are playing with this thing with a while...

**Comment by Debilski** [comment]
> You both seem to prefer the old dark brown?

Not necessarily the brown, but I think it should have the same brightness as the bots and food.

> Also, we are probably the worst to judge, as we are playing with this thing since a while...

Not only that but we are also probably not the best people to design this properly in the first place …

**Comment by otizonaizit** [comment]
> > You both seem to prefer the old dark brown?
> 
> Not necessarily the brown, but I think it should have the same brightness as the bots and food.
> 

What do you mean by "brightness"? You mean the V in HSV coordinates? Give the colors in master, we have for red (0,62,92) and for blue (209,57,85), so the two are already not equally "bright". The brown is (9,54,19). The grey in my last screeshot is (26,6,48).

What do you think of this?
screenshot1

This is halfway between my grey and the original brown in terms of brightness:
It is RGB (89, 86, 84) and HSV (26,6,35).
it seems better to me. It's not so eye-catching like the original brown, which is a bit too much if the walls are thicker, but it's a bit more visible than the gray in my previous example.

**Comment by lschwetlick** [comment]
> do you prefer the version in this PR with thicker walls and filled-in squares or the old version with thin walls and hollow squares? (see above for the screenshots)

Hm, I think filled in and thicker is better... Maybe we can do a survey at the school :)

**Comment by Debilski** [comment]
> What do you mean by "brightness"? You mean the V in HSV coordinates? 

Probably. I think I am not sure what the proper term is for that colour impression.

(Also: On my computer I never really noticed that the original was in fact _brown_ but rather simply dark to me.)

The new version is a little better but still, hmm, maybe we just need to get used to it? The shapes are not really symmetric though.

image

**Comment by Debilski** [comment]
I think I prefer 5153d93 more than the new one. It is still too milky.

**Comment by otizonaizit** [comment]
OK, merging the version that makes walls thicker and the squared filled in, but no changes in color

**Comment by Debilski** [comment]
I think the filling algorithm can still be improved a little:

```
################################
#     #   #    ##  .      .   3#
#.###   # #        #..#..   . 1#
#  . .# # ##.#.   ### ###.######
#  #  # # #       .     .  .   #
# .# ##    . .    ####.#    ## #
#    #  # #  . ##    #.#    . .#
### ## .# ## #####..  .#..     #
#     ..#.  ..##### ## #. ## ###
#. .    #.#    ## .  # #  #    #
# ##    #.####    . .    ## #. #
#   .  .     .       # # #  #  #
######.### ###   .#.## # #. .  #
#0 .   ..#..#        # #   ###.#
#2   .      .  ##    #   #     #
################################
```

**Comment by otizonaizit** [comment]
But that is an illegal layout anyway: it is a disconnected graph... To catch those you would need to either convert to graph or iteratively look for closed chambers. Not worth it in my opinion, because those layouts can not happen in practice.

**Comment by Debilski** [comment]
It’s not disconnected. It just looks disconnected in Tk.

**Pull request merged**
