### PR TITLE
Feature/testing for tournaments

### PR DESCRIPTION
**Pull request by Debilski**
WIP

### CODE REVIEW

**Comment by Debilski** [comment]
Fails on 3.3 and 3.4 because of gratuitous Python 3.5 syntax.

**Comment by Debilski** [comment]
Branch is rather stable now. Going to add a README for the tournament and do some more cleanup.

**Comment by Debilski** [comment]
Interactive mode and spoken output might have some bugs. Other than that it can be tested.

**Comment by otizonaizit** [comment]
Should the tournament not be run in interactive mode by default? That would make sure that we don't make the mistake of running it non-interactively at the school. Even if we have a recovery mode now, I still think the interactive mode should be default. Non interactive is only useful during testing, right?

**Comment by Debilski** [comment]
Maybe. OTOH, one notices rather quickly that the non-interactive mode is on. But you’re correct I guess. Still, I would disable the sound output by default.

**Comment by otizonaizit** [comment]
Or maybe, create a combined option `--live` which would activate 
whatever we deem correct for the live tournament. It could for example 
be equivalent to interaactive, speaking, 300 rounds. What else?

**Comment by Debilski** [comment]
The main reason I removed the default speaking was because I also removed the checks whether the binary was found and the like. It is needed once a year and not really worth cluttering so much of the setup code with if statements.

OTOH I agree that there could be a config shortcut for a bunch of settings (and a more well-thought out configuration system in general).

**Comment by otizonaizit** [comment]
Yeah, but the tournament **is** indeed needed once a year, and that once needs to work out of the box and tell you what is wrong when something is wrong and fail gracefully when nothing better can be done. That's the whole point of automatize it. So, I wouldn't describe the checks as clutter...

**Comment by Debilski** [comment]
Yeah, okay. The problem is that it has gotten harder to test for the *proper* call anyway since we are calling `shlex.split` on whatever string is passed to `--speaker`. I can test that but if the parameters are wrong, we’re out of luck anyway.

Maybe we need to have an interactive configuration script with questions ‘Did you hear a sound?’, ‘How many rounds?’, ‘Where are the teams?’ that gives us back a `tournament-defaults.yaml` to be on the safe side.

**Comment by otizonaizit** [comment]
> Maybe we need to have an interactive configuration script with
> questions ‘Did you hear a sound?’, ‘How many rounds?’, ‘Where are the
> teams?’ that gives us back a `tournament-defaults.yaml` to be on the
> safe side.

That is indeed a good idea. What about `tournament --setup`?

**Comment by Debilski** [comment]
Fine with me. I’ll think about something.

**Comment by Debilski** [comment]
It’s not beautiful but it is something.

**Comment by Debilski** [comment]
Fixing up the logging later. Otherwise, I’ll assume that @jakobj did the review and accepted, right?

**Pull request merged**
