### PR TITLE
Do not return state from move()

### PR DESCRIPTION
**Pull request by keszybz**
Things are simpler if we always initialize the state to be an empty
dictionary, and simply pass the same mutable object always to the move
function. In cases where the player does not actually use the state to
store anything, it can ignore the variable completely. The object also
has always the same type (dict), so there is less chance of trying to
a TypeError.

### CODE REVIEW

**Comment by Debilski** [comment]
I’ll think about it in the coming days. Maybe it’s not as bad as I thought but I am still unsure about if it is nice enough to use with testing.

**Comment by otizonaizit** [comment]
Thanks @keszybz , after talking with you and having seen the students struggling with it, I think it is a good idea to fix the state object to be a dictionary, and not to return it in the move function. I am +1 on this!

**Comment by otizonaizit** [comment]
Before merging, please also address: https://github.com/ASPP/pelita_template/pull/33

**Comment by keszybz** [comment]
Updated to remove the last cases of `if not state`. It is now `if state == {}` everywhere.

**Comment by keszybz** [comment]
Anything else to do here?

**Comment by otizonaizit** [comment]
LGTM

**Comment by keszybz** [comment]
Anything blocking this?

**Comment by Debilski** [comment]
Uhm, multiline `say` … do we want to allow this?

**Comment by keszybz** [comment]
It works, mostly. The font I got was not monospace, so the "underlining" was a bit off.  Maybe some different example would be better.

**Pull request merged**
