### PR TITLE
Controllable replay mode

### LINKED ISSUE #453: Make the replay/snapshots mode first class
Replay mode is broken since the last refactoring. It is possible to fix it badly with a few lines copy/pasta but I think we should do it properly and also add regular tests so that this oversight does not happen again.

### PR DESCRIPTION
**Pull request by Debilski**
Closes #453. (To be rebased after #535 has been merged.)

The ReplayPublisher now includes controller functionality, which means that the Tk viewer can now request the next frame, when it wants to.
This means that we can get rid of the more or less arbitrary sleep functions for proper synchronisation. Additionally, we can now pause the replay and step through it. (Stepping through rounds is not implemented yet.)

Some further restructuring of the init logic in `pelita_main` has also been done.

### CODE REVIEW

**Comment by otizonaizit** [comment]
can you do the rebase and check that everything is still fine? #535 has been merged

**Comment by otizonaizit** [comment]
It would be easier to review without the noise from the `--long-help` thing...

**Comment by Debilski** [comment]
Rebased.

**Comment by Debilski** [comment]
It only works with the Tk viewer (well, any external viewer should work), so it is still some sort of a hack. But it gets rid of the `sleep` therefore it is better. :)

**Pull request merged**
