### PR TITLE
Make it possible to generate mazes with dead ends and chambers

### PR DESCRIPTION
**Pull request by otizonaizit**
This PR does not change the default generation algorithm, so mazes are still generated without dead-ends and chambers by default.

### CODE REVIEW

**Comment by Debilski** [comment]
I suppose this one is uncontroversial :D
Maybe we should also add a test for this in `test_maze_generation.py`? (Btw. I think that line with `* iteration` is kind of useless?)

```
@pytest.mark.parametrize('iteration', range(1,11))
def test_get_new_maze(set_seed, iteration):
    # generate a few mazes and check them for consistency
    local_seed = random.randint(1,2**31-1)*iteration
    maze_str = mg.get_new_maze(8,16,nfood=15,seed=local_seed)
```

**Comment by otizonaizit** [comment]
> I suppose this one is uncontroversial :D Maybe we should also add a test for this in `test_maze_generation.py`?

theoretically yes, but not sure what to test. The maze generation works in a way that a maze is generated and it may or may not contain dead ends (it is not predictable). Then it removes the dead ends. So testing that we can generate a maze with dead ends is kind of useless.

> (Btw. I think that line with `* iteration` is kind of useless?)
> 
> ```
> @pytest.mark.parametrize('iteration', range(1,11))
> def test_get_new_maze(set_seed, iteration):
>     # generate a few mazes and check them for consistency
>     local_seed = random.randint(1,2**31-1)*iteration
>     maze_str = mg.get_new_maze(8,16,nfood=15,seed=local_seed)
> ```

Why? I think the test is generating 10 mazes and verify that they are consistent and are properly formatted. It is a kind of integration test. It could be done only once, but doing it 10 times doesn't hurt either, no? Or are you worried about the test being slow?

**Comment by Debilski** [comment]
> > I suppose this one is uncontroversial :D Maybe we should also add a test for this in test_maze_generation.py?
> 
> theoretically yes, but not sure what to test. The maze generation works in a way that a maze is generated and it may or may not contain dead ends (it is not predictable). Then it removes the dead ends. So testing that we can generate a maze with dead ends is kind of useless.

Yeah, I copied the other test and realised this. But I thought maybe you had a better idea. :)


I mean this line specifically. Why make it a multiple of `iteration`?

    local_seed = random.randint(1, 2**31-1) * iteration

**Comment by otizonaizit** [comment]
> > > I suppose this one is uncontroversial :D Maybe we should also add a test for this in test_maze_generation.py?
> > 
> > 
> > theoretically yes, but not sure what to test. The maze generation works in a way that a maze is generated and it may or may not contain dead ends (it is not predictable). Then it removes the dead ends. So testing that we can generate a maze with dead ends is kind of useless.
> 
> Yeah, I copied the other test and realised this. But I thought maybe you had a better idea. :)
> 
> I mean this line specifically. Why make it a multiple of `iteration`?
> 
> ```
> local_seed = random.randint(1, 2**31-1) * iteration
> ```

to make it more random ;-)

**Review by Debilski — COMMENTED** [review]
LGTM

**Pull request merged**
