### PR TITLE
ENH: Clicking on a field shows the coordinates and other Tk UI enhancements

### PR DESCRIPTION
**Pull request by Debilski**
First commit. Still to do:

- [x] Render the selected field differently
- [x] Not only show the coordinates but also bot ids and whether the field has food or wall

### CODE REVIEW

**Comment by jni** [comment]
This is so cool! =)

**Comment by Debilski** [comment]
Closes #475.

**Comment by Debilski** [comment]
Whoops. Need to do the reciprocal for fps …

**Comment by Debilski** [comment]
QUIT is still not centered but what can you do …

**Pull request merged**
