### PR TITLE
V2.0 Added tests and fixed some bugs in ´play_turn´

### PR DESCRIPTION
**Pull request by lschwetlick**

### CODE REVIEW

**Comment by Debilski** [comment]
I’ll merge and then rebase onto our new branch `pelita-core-2.0`, which is less-conflicting branch name (also did some minor cleanups in that branch). I am going to write an email where I suggest everybody uses this branch now.

**Comment by Debilski** [comment]
@lschwetlick What is your intention with the seedval? To me it seems quite superfluous.

**Comment by lschwetlick** [comment]
I'm not testing everything on all layouts, so by seeding it I can reconstruct which layout stuff went wrong with. I guess I can also just print the layout name or something though...

**Comment by Debilski** [comment]
I think that’s better. I don’t think your approach is actually working, is it? (You just print a random number?)

**Comment by lschwetlick** [comment]
True... Now you say it... something mast have got lost there at some point. Sorry

**Comment by Debilski** [comment]
No problem. As you suggest, I’d just print the layout name and if there turn out to be tests that need more elaborate handling of random numbers, we can look into fixing it in pytest somehow.

**Comment by Debilski** [comment]
Added a solution for the randomness in #569.

**Pull request merged**
