### PR TITLE
Cleanup docs

### PR DESCRIPTION
**Pull request by otizonaizit**
- Removed the now obsolete `groupN` directory from the docs, so that we can finally run `pytest` again without specifying any argument. 
- Update the screeshot of the game, so that it matches the newest UI.
- Changed players for the pelita CLI demo game: use the best builtins we have, so that the game is more interesting to watch

### CODE REVIEW

**Comment by Debilski** [comment]
The SmartRandomPlayers are our best builtins?

**Comment by Debilski** [comment]
Your other cleaning efforts are outdated but ok :)

**Comment by Debilski** [comment]
But seriously. Why the SmartRandomPlayers?

**Comment by otizonaizit** [comment]
>But seriously. Why the SmartRandomPlayers?
>
Change it to something else. I don't care.

**Pull request merged**
